#!/usr/bin/env node
/* Assemble data/i18n/*.json into the site: rewrites the LANGS and STR blocks in site/index.html between the
   i18n markers, and writes data/languages.json. Run after translators or reviewers change a dictionary.
   node server/scripts/i18n-build.js            (from projects/ug) */
const fs = require('fs'), path = require('path');
const ROOT = path.resolve(__dirname, '..', '..');
const DIR = path.join(ROOT, 'data', 'i18n');
const SITE = path.join(ROOT, 'site', 'index.html');
const ORDER = { // picker groups, in the order they appear
  'Uganda · Central': ['lg'], 'Uganda · East': ['xog', 'myx', 'gwr', 'lsm', 'teo', 'kpz'], 'Uganda · North': ['ach', 'laj', 'kdi', 'kdj'],
  'Uganda · West Nile': ['alz', 'lgg', 'mhi', 'keo'], 'Uganda · West': ['nyn', 'cgg', 'ttj', 'nyo', 'koo'],
  'East Africa · Africa': ['sw', 'rw', 'so', 'am', 'ar', 'ln', 'ha', 'zu'],
  'World': ['en', 'fr', 'de', 'it', 'es', 'es-MX', 'pt', 'pt-BR', 'ru', 'zh-Hans', 'ja', 'ko', 'hi'],
};
const en = JSON.parse(fs.readFileSync(path.join(DIR, 'en.json'), 'utf8'));
const keys = Object.keys(en.strings);
const files = fs.readdirSync(DIR).filter(f => f.endsWith('.json')).map(f => f.replace(/\.json$/, ''));
const langs = {}, str = {};
for (const k of keys) str[k] = { en: en.strings[k].text };
const report = [];
for (const code of files) {
  if (code === 'en') { langs.en = { name: 'English', native: 'English', region: 'World', dir: 'ltr', script: 'Latin', confidence: 'complete', uncertain: 0, missing: 0 }; continue; }
  const d = JSON.parse(fs.readFileSync(path.join(DIR, code + '.json'), 'utf8'));
  let missing = 0, bad = 0;
  for (const k of keys) {
    const v = d.strings && d.strings[k];
    if (typeof v !== 'string' || !v.trim()) { missing++; continue; }
    if (en.strings[k].html) { // tags must survive translation
      const tags = s => (s.match(/<\/?[a-z]+/g) || []).sort().join(',');
      if (tags(v) !== tags(en.strings[k].text)) { bad++; continue; }
    }
    str[k][code] = v;
  }
  langs[code] = { name: d.name, native: d.native, region: d.region || '', family: d.family || '', dir: d.dir || 'ltr', script: d.script || 'Latin', confidence: d.confidence || 'draft', note: d.translator_note || '', uncertain: (d.uncertain || []).length, missing, review: d.review_note || '' };
  report.push(`${code.padEnd(8)} ${String(keys.length - missing).padStart(3)}/${keys.length}  ${String(bad).padStart(2)} bad-tags  ${String((d.uncertain || []).length).padStart(3)} uncertain  ${(d.confidence || 'draft').padEnd(9)} ${d.name}`);
}
// order LANGS by the picker groups; unknown codes go last
const ordered = {};
for (const [group, codes] of Object.entries(ORDER)) for (const c of codes) if (langs[c]) ordered[c] = { ...langs[c], group };
for (const c of Object.keys(langs)) if (!ordered[c]) ordered[c] = { ...langs[c], group: 'Other' };
let site = fs.readFileSync(SITE, 'utf8');
const A = '/* i18n:begin (generated by server/scripts/i18n-build.js from data/i18n/*.json; do not edit by hand) */';
const B = '/* i18n:end */';
const block = `${A}\nconst LANGS = ${JSON.stringify(ordered)};\nconst STR = ${JSON.stringify(str)};\n${B}`;
if (site.includes(A)) {
  site = site.slice(0, site.indexOf(A)) + block + site.slice(site.indexOf(B) + B.length);
} else {
  const a = site.indexOf('const LANGS = {'); const b = site.indexOf('\n};', site.indexOf('const STR = {')) + 3;
  if (a < 0 || b < 3) throw new Error('LANGS/STR block not found');
  site = site.slice(0, a) + block + site.slice(b);
}
fs.writeFileSync(SITE, site);
fs.writeFileSync(path.join(ROOT, 'data', 'languages.json'), JSON.stringify({ generated: new Date().toISOString().slice(0, 10), source: 'data/i18n/*.json via server/scripts/i18n-build.js', keys: keys.length, languages: ordered }, null, 1));
console.log(report.join('\n'));
console.log(`${Object.keys(ordered).length} languages, ${keys.length} keys, STR ${Math.round(JSON.stringify(str).length / 1024)} KB`);
